<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RQ6NMQQ" failures="1" tests="1" name="Test Edge" time="17.281" errors="0" timestamp="2024-11-06T10:34:09 IST">
  <testcase classname="testCases.AccountRegistrationTC" name="verify_account_registration" time="10.505">
    <failure type="java.lang.AssertionError" message="Test failed due to an exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to an exception.
at testCases.AccountRegistrationTC.verify_account_registration(AccountRegistrationTC.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verify_account_registration -->
</testsuite> <!-- Test Edge -->
